"""phase_u_continuity

Revision ID: 39f1f5817922
Revises: 
Create Date: 2026-09-13 08:33:39.655011+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f1f5817922'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_principal_id', sa.String(length=26), nullable=True),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('event_kind', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_principal_id'), 'audit_events', ['actor_principal_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_kind', 'audit_events', ['event_kind'], unique=False)
    op.create_index('ix_audit_events_principal', 'audit_events', ['actor_principal_id'], unique=False)
    op.create_table('principals',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_messages',
    sa.Column('interface_kind', sa.String(length=32), nullable=False),
    sa.Column('interface_message_id', sa.String(length=256), nullable=False),
    sa.Column('principal_id', sa.String(length=26), nullable=True),
    sa.Column('execution_id', sa.String(length=26), nullable=True),
    sa.Column('objective_id', sa.String(length=26), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('request_text', sa.String(length=2000), nullable=True),
    sa.Column('response_text', sa.String(length=5000), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interface_kind', 'interface_message_id', name='uq_processed_messages_interface_id')
    )
    op.create_index('ix_processed_messages_execution', 'processed_messages', ['execution_id'], unique=False)
    op.create_index('ix_processed_messages_principal', 'processed_messages', ['principal_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('permissions', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_table('conversations',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('interface_kind', sa.String(length=32), nullable=False),
    sa.Column('objective_id', sa.String(length=26), nullable=True),
    sa.Column('last_execution_id', sa.String(length=26), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_last_message', 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_principal_id'), 'conversations', ['principal_id'], unique=False)
    op.create_index('ix_conversations_principal_status', 'conversations', ['principal_id', 'status'], unique=False)
    op.create_table('executions',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_principal', 'executions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_executions_principal_id'), 'executions', ['principal_id'], unique=False)
    op.create_index('ix_executions_status', 'executions', ['status'], unique=False)
    op.create_table('memory_records',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=64), nullable=False),
    sa.Column('source_execution_id', sa.String(length=26), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('superseded_by', sa.String(length=26), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sensitivity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_principal_kind', 'memory_records', ['principal_id', 'kind'], unique=False)
    op.create_index('ix_memory_principal_status', 'memory_records', ['principal_id', 'status'], unique=False)
    op.create_index(op.f('ix_memory_records_principal_id'), 'memory_records', ['principal_id'], unique=False)
    op.create_index('ix_memory_superseded_by', 'memory_records', ['superseded_by'], unique=False)
    op.create_table('objectives',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('execution_id', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_objectives_principal', 'objectives', ['principal_id'], unique=False)
    op.create_index(op.f('ix_objectives_principal_id'), 'objectives', ['principal_id'], unique=False)
    op.create_index('ix_objectives_status', 'objectives', ['status'], unique=False)
    op.create_table('principal_credentials',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_principal_credentials_kind_value')
    )
    op.create_index(op.f('ix_principal_credentials_principal_id'), 'principal_credentials', ['principal_id'], unique=False)
    op.create_table('principal_roles',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('role_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'role_id', name='uq_principal_roles')
    )
    op.create_index(op.f('ix_principal_roles_principal_id'), 'principal_roles', ['principal_id'], unique=False)
    op.create_index(op.f('ix_principal_roles_role_id'), 'principal_roles', ['role_id'], unique=False)
    op.create_table('execution_steps',
    sa.Column('execution_id', sa.String(length=26), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('capability_name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_steps_exec', 'execution_steps', ['execution_id', 'step_number'], unique=False)
    op.create_index(op.f('ix_execution_steps_execution_id'), 'execution_steps', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_steps_execution_id'), table_name='execution_steps')
    op.drop_index('ix_execution_steps_exec', table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index(op.f('ix_principal_roles_role_id'), table_name='principal_roles')
    op.drop_index(op.f('ix_principal_roles_principal_id'), table_name='principal_roles')
    op.drop_table('principal_roles')
    op.drop_index(op.f('ix_principal_credentials_principal_id'), table_name='principal_credentials')
    op.drop_table('principal_credentials')
    op.drop_index('ix_objectives_status', table_name='objectives')
    op.drop_index(op.f('ix_objectives_principal_id'), table_name='objectives')
    op.drop_index('ix_objectives_principal', table_name='objectives')
    op.drop_table('objectives')
    op.drop_index('ix_memory_superseded_by', table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_principal_id'), table_name='memory_records')
    op.drop_index('ix_memory_principal_status', table_name='memory_records')
    op.drop_index('ix_memory_principal_kind', table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index('ix_executions_status', table_name='executions')
    op.drop_index(op.f('ix_executions_principal_id'), table_name='executions')
    op.drop_index('ix_executions_principal', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_conversations_principal_status', table_name='conversations')
    op.drop_index(op.f('ix_conversations_principal_id'), table_name='conversations')
    op.drop_index('ix_conversations_last_message', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('roles')
    op.drop_index('ix_processed_messages_principal', table_name='processed_messages')
    op.drop_index('ix_processed_messages_execution', table_name='processed_messages')
    op.drop_table('processed_messages')
    op.drop_table('principals')
    op.drop_index('ix_audit_events_principal', table_name='audit_events')
    op.drop_index('ix_audit_events_kind', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_principal_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
