"""phase_cde_state_identity_authority

Revision ID: 83ad925f3231
Revises: 
Create Date: 2026-09-12 22:04:03.254703+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ad925f3231'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_principal_id', sa.String(length=26), nullable=True),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('event_kind', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_principal_id'), 'audit_events', ['actor_principal_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_kind', 'audit_events', ['event_kind'], unique=False)
    op.create_index('ix_audit_events_principal', 'audit_events', ['actor_principal_id'], unique=False)
    op.create_table('principals',
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_table('principal_credentials',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_principal_credentials_kind_value')
    )
    op.create_index(op.f('ix_principal_credentials_principal_id'), 'principal_credentials', ['principal_id'], unique=False)
    op.create_table('principal_roles',
    sa.Column('principal_id', sa.String(length=26), nullable=False),
    sa.Column('role_id', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'role_id', name='uq_principal_roles')
    )
    op.create_index(op.f('ix_principal_roles_principal_id'), 'principal_roles', ['principal_id'], unique=False)
    op.create_index(op.f('ix_principal_roles_role_id'), 'principal_roles', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_principal_roles_role_id'), table_name='principal_roles')
    op.drop_index(op.f('ix_principal_roles_principal_id'), table_name='principal_roles')
    op.drop_table('principal_roles')
    op.drop_index(op.f('ix_principal_credentials_principal_id'), table_name='principal_credentials')
    op.drop_table('principal_credentials')
    op.drop_table('roles')
    op.drop_table('principals')
    op.drop_index('ix_audit_events_principal', table_name='audit_events')
    op.drop_index('ix_audit_events_kind', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_principal_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
