"""SQLAlchemy 2.0 declarative base + shared mixins.

All WAX ORM models inherit from `Base`. The mixins provide:
- ULID-based primary keys (lexicographically sortable, time-ordered)
- created_at / updated_at timestamps (UTC)
- Soft-delete support (deleted_at) where applicable

Architectural principle: identifiers are opaque strings, not integers.
This prevents enumeration attacks and makes IDs safe to expose in logs,
URLs, and external interfaces.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import DateTime, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base for all WAX ORM models."""


class TimestampMixin:
    """Adds created_at + updated_at columns, both UTC, both nullable=False.

    SQLAlchemy's `onupdate` fires on UPDATE statements. The application layer
    must ensure updates go through SQLAlchemy ORM (not raw SQL) for this to
    work.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


class ULIDPrimaryKeyMixin:
    """Adds a ULID string primary key column.

    ULIDs are 26-character lexicographically-sortable identifiers. They are:
    - Time-ordered (sort by string = sort by creation time)
    - URL-safe (no special chars)
    - Collision-resistant (80 bits of entropy)
    - Opaque (cannot be enumerated like sequential integers)
    """

    id: Mapped[str] = mapped_column(
        String(26),
        primary_key=True,
        # ULIDs are generated by the application layer, not the DB.
        # This is intentional: it lets us return the ID before INSERT,
        # simplifying repository patterns.
    )


def utc_now() -> datetime:
    """Return current UTC time. Used as a default factory."""
    return datetime.now(timezone.utc)
